//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientTestProject.TokenServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VwDoctorsApointment", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class VwDoctorsApointment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int DoctorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameSurnameField;
        
        private System.Nullable<bool> ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatienNameSurnameField;
        
        private System.Nullable<System.DateTime> ApointmentDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DoctorId {
            get {
                return this.DoctorIdField;
            }
            set {
                if ((this.DoctorIdField.Equals(value) != true)) {
                    this.DoctorIdField = value;
                    this.RaisePropertyChanged("DoctorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NameSurname {
            get {
                return this.NameSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameSurnameField, value) != true)) {
                    this.NameSurnameField = value;
                    this.RaisePropertyChanged("NameSurname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<bool> Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PatienNameSurname {
            get {
                return this.PatienNameSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.PatienNameSurnameField, value) != true)) {
                    this.PatienNameSurnameField = value;
                    this.RaisePropertyChanged("PatienNameSurname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<System.DateTime> ApointmentDate {
            get {
                return this.ApointmentDateField;
            }
            set {
                if ((this.ApointmentDateField.Equals(value) != true)) {
                    this.ApointmentDateField = value;
                    this.RaisePropertyChanged("ApointmentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TokenServiceReference.TokenSoap")]
    public interface TokenSoap {
        
        // CODEGEN: Generating message contract since element name GetNowResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNow", ReplyAction="*")]
        ClientTestProject.TokenServiceReference.GetNowResponse GetNow(ClientTestProject.TokenServiceReference.GetNowRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNow", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientTestProject.TokenServiceReference.GetNowResponse> GetNowAsync(ClientTestProject.TokenServiceReference.GetNowRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetToken", ReplyAction="*")]
        ClientTestProject.TokenServiceReference.GetTokenResponse GetToken(ClientTestProject.TokenServiceReference.GetTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetToken", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientTestProject.TokenServiceReference.GetTokenResponse> GetTokenAsync(ClientTestProject.TokenServiceReference.GetTokenRequest request);
        
        // CODEGEN: Generating message contract since element name SecretKey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDoctorsApointments", ReplyAction="*")]
        ClientTestProject.TokenServiceReference.GetDoctorsApointmentsResponse GetDoctorsApointments(ClientTestProject.TokenServiceReference.GetDoctorsApointmentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDoctorsApointments", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientTestProject.TokenServiceReference.GetDoctorsApointmentsResponse> GetDoctorsApointmentsAsync(ClientTestProject.TokenServiceReference.GetDoctorsApointmentsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNow", Namespace="http://tempuri.org/", Order=0)]
        public ClientTestProject.TokenServiceReference.GetNowRequestBody Body;
        
        public GetNowRequest() {
        }
        
        public GetNowRequest(ClientTestProject.TokenServiceReference.GetNowRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetNowRequestBody {
        
        public GetNowRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNowResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNowResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientTestProject.TokenServiceReference.GetNowResponseBody Body;
        
        public GetNowResponse() {
        }
        
        public GetNowResponse(ClientTestProject.TokenServiceReference.GetNowResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNowResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetNowResult;
        
        public GetNowResponseBody() {
        }
        
        public GetNowResponseBody(string GetNowResult) {
            this.GetNowResult = GetNowResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetToken", Namespace="http://tempuri.org/", Order=0)]
        public ClientTestProject.TokenServiceReference.GetTokenRequestBody Body;
        
        public GetTokenRequest() {
        }
        
        public GetTokenRequest(ClientTestProject.TokenServiceReference.GetTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ApiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SecretKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Password;
        
        public GetTokenRequestBody() {
        }
        
        public GetTokenRequestBody(string ApiKey, string SecretKey, string Username, string Password) {
            this.ApiKey = ApiKey;
            this.SecretKey = SecretKey;
            this.Username = Username;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTokenResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientTestProject.TokenServiceReference.GetTokenResponseBody Body;
        
        public GetTokenResponse() {
        }
        
        public GetTokenResponse(ClientTestProject.TokenServiceReference.GetTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTokenResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string OMessage;
        
        public GetTokenResponseBody() {
        }
        
        public GetTokenResponseBody(string GetTokenResult, string OMessage) {
            this.GetTokenResult = GetTokenResult;
            this.OMessage = OMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDoctorsApointmentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDoctorsApointments", Namespace="http://tempuri.org/", Order=0)]
        public ClientTestProject.TokenServiceReference.GetDoctorsApointmentsRequestBody Body;
        
        public GetDoctorsApointmentsRequest() {
        }
        
        public GetDoctorsApointmentsRequest(ClientTestProject.TokenServiceReference.GetDoctorsApointmentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDoctorsApointmentsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SecretKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Token;
        
        public GetDoctorsApointmentsRequestBody() {
        }
        
        public GetDoctorsApointmentsRequestBody(string SecretKey, string Token) {
            this.SecretKey = SecretKey;
            this.Token = Token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDoctorsApointmentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDoctorsApointmentsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientTestProject.TokenServiceReference.GetDoctorsApointmentsResponseBody Body;
        
        public GetDoctorsApointmentsResponse() {
        }
        
        public GetDoctorsApointmentsResponse(ClientTestProject.TokenServiceReference.GetDoctorsApointmentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDoctorsApointmentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientTestProject.TokenServiceReference.VwDoctorsApointment[] GetDoctorsApointmentsResult;
        
        public GetDoctorsApointmentsResponseBody() {
        }
        
        public GetDoctorsApointmentsResponseBody(ClientTestProject.TokenServiceReference.VwDoctorsApointment[] GetDoctorsApointmentsResult) {
            this.GetDoctorsApointmentsResult = GetDoctorsApointmentsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TokenSoapChannel : ClientTestProject.TokenServiceReference.TokenSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TokenSoapClient : System.ServiceModel.ClientBase<ClientTestProject.TokenServiceReference.TokenSoap>, ClientTestProject.TokenServiceReference.TokenSoap {
        
        public TokenSoapClient() {
        }
        
        public TokenSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TokenSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TokenSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TokenSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientTestProject.TokenServiceReference.GetNowResponse ClientTestProject.TokenServiceReference.TokenSoap.GetNow(ClientTestProject.TokenServiceReference.GetNowRequest request) {
            return base.Channel.GetNow(request);
        }
        
        public string GetNow() {
            ClientTestProject.TokenServiceReference.GetNowRequest inValue = new ClientTestProject.TokenServiceReference.GetNowRequest();
            inValue.Body = new ClientTestProject.TokenServiceReference.GetNowRequestBody();
            ClientTestProject.TokenServiceReference.GetNowResponse retVal = ((ClientTestProject.TokenServiceReference.TokenSoap)(this)).GetNow(inValue);
            return retVal.Body.GetNowResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientTestProject.TokenServiceReference.GetNowResponse> ClientTestProject.TokenServiceReference.TokenSoap.GetNowAsync(ClientTestProject.TokenServiceReference.GetNowRequest request) {
            return base.Channel.GetNowAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientTestProject.TokenServiceReference.GetNowResponse> GetNowAsync() {
            ClientTestProject.TokenServiceReference.GetNowRequest inValue = new ClientTestProject.TokenServiceReference.GetNowRequest();
            inValue.Body = new ClientTestProject.TokenServiceReference.GetNowRequestBody();
            return ((ClientTestProject.TokenServiceReference.TokenSoap)(this)).GetNowAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientTestProject.TokenServiceReference.GetTokenResponse ClientTestProject.TokenServiceReference.TokenSoap.GetToken(ClientTestProject.TokenServiceReference.GetTokenRequest request) {
            return base.Channel.GetToken(request);
        }
        
        public string GetToken(string ApiKey, string SecretKey, string Username, string Password, out string OMessage) {
            ClientTestProject.TokenServiceReference.GetTokenRequest inValue = new ClientTestProject.TokenServiceReference.GetTokenRequest();
            inValue.Body = new ClientTestProject.TokenServiceReference.GetTokenRequestBody();
            inValue.Body.ApiKey = ApiKey;
            inValue.Body.SecretKey = SecretKey;
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            ClientTestProject.TokenServiceReference.GetTokenResponse retVal = ((ClientTestProject.TokenServiceReference.TokenSoap)(this)).GetToken(inValue);
            OMessage = retVal.Body.OMessage;
            return retVal.Body.GetTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientTestProject.TokenServiceReference.GetTokenResponse> ClientTestProject.TokenServiceReference.TokenSoap.GetTokenAsync(ClientTestProject.TokenServiceReference.GetTokenRequest request) {
            return base.Channel.GetTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientTestProject.TokenServiceReference.GetTokenResponse> GetTokenAsync(string ApiKey, string SecretKey, string Username, string Password) {
            ClientTestProject.TokenServiceReference.GetTokenRequest inValue = new ClientTestProject.TokenServiceReference.GetTokenRequest();
            inValue.Body = new ClientTestProject.TokenServiceReference.GetTokenRequestBody();
            inValue.Body.ApiKey = ApiKey;
            inValue.Body.SecretKey = SecretKey;
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            return ((ClientTestProject.TokenServiceReference.TokenSoap)(this)).GetTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientTestProject.TokenServiceReference.GetDoctorsApointmentsResponse ClientTestProject.TokenServiceReference.TokenSoap.GetDoctorsApointments(ClientTestProject.TokenServiceReference.GetDoctorsApointmentsRequest request) {
            return base.Channel.GetDoctorsApointments(request);
        }
        
        public ClientTestProject.TokenServiceReference.VwDoctorsApointment[] GetDoctorsApointments(string SecretKey, string Token) {
            ClientTestProject.TokenServiceReference.GetDoctorsApointmentsRequest inValue = new ClientTestProject.TokenServiceReference.GetDoctorsApointmentsRequest();
            inValue.Body = new ClientTestProject.TokenServiceReference.GetDoctorsApointmentsRequestBody();
            inValue.Body.SecretKey = SecretKey;
            inValue.Body.Token = Token;
            ClientTestProject.TokenServiceReference.GetDoctorsApointmentsResponse retVal = ((ClientTestProject.TokenServiceReference.TokenSoap)(this)).GetDoctorsApointments(inValue);
            return retVal.Body.GetDoctorsApointmentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientTestProject.TokenServiceReference.GetDoctorsApointmentsResponse> ClientTestProject.TokenServiceReference.TokenSoap.GetDoctorsApointmentsAsync(ClientTestProject.TokenServiceReference.GetDoctorsApointmentsRequest request) {
            return base.Channel.GetDoctorsApointmentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientTestProject.TokenServiceReference.GetDoctorsApointmentsResponse> GetDoctorsApointmentsAsync(string SecretKey, string Token) {
            ClientTestProject.TokenServiceReference.GetDoctorsApointmentsRequest inValue = new ClientTestProject.TokenServiceReference.GetDoctorsApointmentsRequest();
            inValue.Body = new ClientTestProject.TokenServiceReference.GetDoctorsApointmentsRequestBody();
            inValue.Body.SecretKey = SecretKey;
            inValue.Body.Token = Token;
            return ((ClientTestProject.TokenServiceReference.TokenSoap)(this)).GetDoctorsApointmentsAsync(inValue);
        }
    }
}
