//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBlog
    {
        public int BlogId { get; set; }
        public string BlogTitle { get; set; }
        public string SmallDescription { get; set; }
        public string Description { get; set; }
        public string ImagePath { get; set; }
        public string BlogLink { get; set; }
    }
}
