//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMailList
    {
        public int Id { get; set; }
        public string Mail { get; set; }
    
        public virtual TblMailList TblMailList1 { get; set; }
        public virtual TblMailList TblMailList2 { get; set; }
    }
}
