//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalDataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbWebPortalEntities : DbContext
    {
        public DbWebPortalEntities()
            : base("name=DbWebPortalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblMailList> TblMailList { get; set; }
        public virtual DbSet<TblOpeningHours> TblOpeningHours { get; set; }
        public virtual DbSet<VWOpeningHours> VWOpeningHours { get; set; }
        public virtual DbSet<TblDoctors> TblDoctors { get; set; }
        public virtual DbSet<TblApointment> TblApointment { get; set; }
        public virtual DbSet<TblBlog> TblBlog { get; set; }
        public virtual DbSet<TblApiUsers> TblApiUsers { get; set; }
        public virtual DbSet<VwDoctorsApointment> VwDoctorsApointment { get; set; }
    }
}
